### PR TITLE
Wrong start extent

### PR DESCRIPTION
**Pull request by rmarzocchi84**
I have a QGIS project with EPSG:32632 and on th efly projection enable.

QGIS Mapserver works well: layers are correctly overlayed.

The problem is with QGIS Web Client: the map extent is calculated without reprojecting, the 3857 CRS prevails and the start  extent is wrong.
Qgis Web Client picks the first layer it finds in the GetCapabilities and uses the bounding box of this layer, without reprojecting from layer SRS to map SRS considering layer coordinates in EPSG 3857.

### CODE REVIEW

**Comment by bstroebl** [comment]
Hi Roberto,
is this supposed to be a pull request or a ticket/question?
Generally you should use the same CRS for layers, project and QWC

**Comment by rmarzocchi84** [comment]
But use 3857 CRS for the layers can be a problem, while for QWC it is 
correct in order to see OSM layers

R


Il 10/02/2016 11:25, bstroebl ha scritto:
>
> Hi Roberto,
> is this supposed to be a pull request or a ticket/question?
> Generally you should use the same CRS for layers, project and QWC
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/qgis/QGIS-Web-Client/pull/151#issuecomment-182297542>.
>

-- 
Eng. Roberto Marzocchi, PhD
GIS Project Coordinator
Gter srl Innovazione in Geomatica, Gnss e Gis (Unige spin-off)
Piazza De Marini 3/61 - 16123 Genova
P.IVA/CF 01998770992
ph: 010-8694830 - mob: 349-8786575
E-mail: roberto.marzocchi@gter.it
skype: roberto.marzocchi84
www.gter.it

--
Gter social
www.twitter.com/Gteronline - www.facebook.com/Gteronline - https://plus.google.com/+GterIt/posts
www.linkedin.com/company/gter-srl-innovazione-in-geomatica-gnss-e-gis

-----------------------------------------------------------------
Please consider the environment before printing this email!

**Comment by bstroebl** [comment]
So you mean your layer and project are the same CRS (EPSG:32632) but QWC uses EPSG:3857 because of OSM-layers. Are you passing in a start extent or are you talking about the maxExtent derived from GetCapabilities?

**Comment by rmarzocchi84** [comment]
Il 10/02/2016 11:45, bstroebl ha scritto:
>
> So you mean your layer and project are the same CRS (EPSG:32632) but 
> QWC uses EPSG:3857 because of OSM-layers.
>
Exactly
>
> Are you passing in a start extent or are you talking about the 
> maxExtent derived from GetCapabilities?
>
the problem seem to be in the startextent that use the UTM coordinates 
(32632) but consider is as Pseudo-Mercator (3857)

The layers are correctly placed

R
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/qgis/QGIS-Web-Client/pull/151#issuecomment-182308914>.
>

-- 
Eng. Roberto Marzocchi, PhD
GIS Project Coordinator
Gter srl Innovazione in Geomatica, Gnss e Gis (Unige spin-off)
Piazza De Marini 3/61 - 16123 Genova
P.IVA/CF 01998770992
ph: 010-8694830 - mob: 349-8786575
E-mail: roberto.marzocchi@gter.it
skype: roberto.marzocchi84
www.gter.it

--
Gter social
www.twitter.com/Gteronline - www.facebook.com/Gteronline - https://plus.google.com/+GterIt/posts
www.linkedin.com/company/gter-srl-innovazione-in-geomatica-gnss-e-gis

-----------------------------------------------------------------
Please consider the environment before printing this email!

**Comment by bstroebl** [comment]
AFAIK the start coordinates being passed in must be in QWC's CRS coordinates, because you are sending them to QWC and not QGIS server.

**Comment by rmarzocchi84** [comment]
But where I can pass the CRS coordinates to QWC?

**Comment by bstroebl** [comment]
in the URL you can pass startExtent=...

**Comment by rmarzocchi84** [comment]
Ok, but I think that this is not user-friendly. 

I suggest to open a ticket (similar to this.. https://hub.qgis.org/issues/3964) 

where? on github or qgis?

**Comment by bstroebl** [comment]
What is not user friendly? Passing in the startExtent in QWC's CRS coordinates? For me this seems user friendly because that's what I would expect. Why should I pass them in in a completely different CRS? One could think about an additional (optional) parameter declaring the CRS of the passed in coordinates. If set, QWC reprojects them to its own CRS if the two do not match.
Tickets go to qgis.

**Comment by rmarzocchi84** [comment]
Il 10/02/2016 13:03, bstroebl ha scritto:
>
> What is not user friendly? Passing in the startExtent in QWC's CRS 
> coordinates? For me this seems user friendly because that's what I 
> would expect. Why should I pass them in in a completely different CRS?
>
TO do thi sthe user need to:
1) check che coordinate of QGIS project
2) translate them in QWC CRS
3) write in URL

> One could think about an additional (optional) parameter declaring the 
> CRS of the passed in coordinates. If set, QWC reprojects them to its 
> own CRS if the two do not match.
>
The best thing is that QWC read the QGIS project CRS --> then QWC 
reprojects to its own CRS if the two do not match and all it is automatic!



> Tickets go to qgis.
>
Ok I open a ticket


> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/qgis/QGIS-Web-Client/pull/151#issuecomment-182336119>.
>

-- 
Eng. Roberto Marzocchi, PhD
GIS Project Coordinator
Gter srl Innovazione in Geomatica, Gnss e Gis (Unige spin-off)
Piazza De Marini 3/61 - 16123 Genova
P.IVA/CF 01998770992
ph: 010-8694830 - mob: 349-8786575
E-mail: roberto.marzocchi@gter.it
skype: roberto.marzocchi84
www.gter.it

--
Gter social
www.twitter.com/Gteronline - www.facebook.com/Gteronline - https://plus.google.com/+GterIt/posts
www.linkedin.com/company/gter-srl-innovazione-in-geomatica-gnss-e-gis

-----------------------------------------------------------------
Please consider the environment before printing this email!

**Comment by bstroebl** [comment]
To do this one could also:
Open one's desktop GIS, set it to QWC's CRS and directly read the extent needed

Concerning your proposed solution that QWC should assume that the extent passed in is in the project's CRS I have two notes:
1) AFAIK QWC can only read the project's CRS if it uses GetProjectSettings, not with GetCapabilities; generally a WMS server only lists the CRS it can server the layers and does not have a CRS of it's own (AFAIK, too)
2) how could one pass in QWC coordinates then, as e.g. permalink does?

**Pull request closed without merging**
